Max upload size config
Start9Labs/cryptpad-wrapper pull request #23
Opened 2023-02-25 01:44 UTC by Dominion5254

Add maxUploadSize to available config options

2023-02-27 15:16 UTC, chrisguida commented
Needs a migration, or needs max-upload-size to be nullable

2023-02-27 15:16 UTC, chrisguida requested changes
see comment

2023-02-27 21:03 UTC, Dominion5254 commented
Updated to set max-upload-size to nullable

2023-02-28 19:52 UTC, chrisguida approved these changes
Looks good, ship it

2023-02-28 21:05 UTC, merged